name: Update Docker Hub README everytime it changes on master

env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    APP: reddcoind
    DOCKER_REPOSITORY: reddcoincore
on:
  push:
    branches: [ 'master' ]
    paths:
      - README.md
      - '.github/workflows/update-readme.yml'

jobs:
  sync:
    name: Update README to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: echo ::set-env name=SLUG::"$(echo "$DOCKER_REPOSITORY/$APP")"

      - name: Sync README.md and Description to Docker Hub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASS }}
          slug: ${{ env.SLUG }}
          description: true
